const REACT_APP_API_URL: string = 'https://aideindustries.ml/'
const REACT_APP_API_KEY: string = 'ace68d53680920b040d5e419b048c4d99be6d65f'
const REACT_APP_ONION_SLOTS_LINK: string =
    'https://beta-admin.glovoapp.com/couriers/schedule/slots/'
const REACT_APP_FIREBASE_API_KEY = 'AIzaSyAYzjcYBshWL0mRNK21lH5kmtwybqySIAY'
const REACT_APP_FIREBASE_AUTH_DOMAIN = 'aide-application.firebaseapp.com'
const REACT_APP_FIREBASE_PROJECT_ID = 'aide-application'
const REACT_APP_FIREBASE_STORAGE_BUCKET = 'aide-application.appspot.com'
const REACT_APP_FIREBASE_SENDER_ID = '561150940236'
const REACT_APP_FIREBASE_APP_ID = '1:561150940236:web:baf8992cb15c9f6ee850e9'

export {
    REACT_APP_API_URL,
    REACT_APP_API_KEY,
    REACT_APP_ONION_SLOTS_LINK,
    REACT_APP_FIREBASE_API_KEY,
    REACT_APP_FIREBASE_AUTH_DOMAIN,
    REACT_APP_FIREBASE_PROJECT_ID,
    REACT_APP_FIREBASE_STORAGE_BUCKET,
    REACT_APP_FIREBASE_SENDER_ID,
    REACT_APP_FIREBASE_APP_ID,
}
