const REACT_APP_AIDE_API_URL: string = 'https://aideindustries.tk/v2/'
const REACT_APP_AIDE_API_KEY: string =
    '73277e30f55af17c9d6377d86dce6d244483efdd'
const REACT_APP_ADMIN_API_GLOVOAPP_URL = 'https://adminapi.glovoapp.com'
const REACT_APP_CORS_ADMIN_API_GLOVOAPP_URL =
    'https://cors-anywhere.herokuapp.com/https://adminapi.glovoapp.com'

const REACT_APP_ONION_SLOTS_LINK: string =
    'https://beta-admin.glovoapp.com/couriers/schedule/slots/'

const REACT_APP_FIREBASE_API_KEY = 'AIzaSyAYzjcYBshWL0mRNK21lH5kmtwybqySIAY'
const REACT_APP_FIREBASE_AUTH_DOMAIN = 'aide-application.firebaseapp.com'
const REACT_APP_FIREBASE_PROJECT_ID = 'aide-application'
const REACT_APP_FIREBASE_STORAGE_BUCKET = 'aide-application.appspot.com'
const REACT_APP_FIREBASE_SENDER_ID = '561150940236'
const REACT_APP_FIREBASE_APP_ID = '1:561150940236:web:baf8992cb15c9f6ee850e9'

const REACT_APP_GOOGLE_SPREADSHEET_SCHEDULE_ACTIONS_LOG_PRIVATE_KEY =
    '-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDHKxVLGw/Atmw6\nHQZPv6FereHuYRfpJSCNf6wMx5Qxcf0XmzhdN6fPvHFWXgCFc6pqDxcpPd4YmhZs\nuOE6SWil5q8PF+zXySm/CC/20xPtXng9NBY+yNrL8Cem6kOIZEeZ1mQugQaYAMrl\n5HRG3sJ5U32oyCqGo5Rle5SK9HhjILnLKufmWdICd7tfv7ar/QzpujIkmnDas1nB\n3Uu97w5ktn0QjW3qLVrcqsruObPN2nZtEWvnjfCQTd3OLVVnglqziXE5PSZCg3cx\nONRw7qS+aqrdpryuSZKCHu50c9g7xHVUEGlZ6/VhjfaWMbhPMF3bIBDJKPdedmMW\ncamr1Z2rAgMBAAECggEAB21n4eEkeT9UUeZ7McYnsmwxnL4qMhucVyqHtAJNWHqz\nwYmcVH2a2HhikaH3ywJBPKtLZdJU0f4NEAjk/VN3f5hWtu1he7qYv/MCNuYwPA3l\n1gJ3QegjoK9YCzV5R0DWGrqQCdvt7wU4i9I1M99iyTt/2Cd+zn6TLiWpqHTteGTT\nF4thjLGSP9IW0pin4F2bhAWkJBGoQtvHM0yEX3arbN0gEYaDFD+yOSnJafmUJMqa\n0iZuBBatF1udC77rJXfpVIfgAu6FiXTVNuv3JqZiGpEPAK9GlQbmstUOYsxyScDs\nSQHr1Zx/1SPL0JWcCjR5veFbjpNSkAH6upNIboudAQKBgQD7+Ui2sfRnaKQZUzWa\n9AHrClects8CymEWY5eWxIHjZKPlS3zTMNoAZTLqiTrz+0graNco+QVgw3Gy3iNG\n+RIV2RSc4PYu4DNawp1ZqZ7Gw71XdbRN3KzWAcexuEWG9ppkJJJlhthiW8dAVcPy\nDAxF66fw0ESExeC9kKB9R5E+YQKBgQDKWctz0MUOR0BK1Af2vbD7/kTRlWjvDqQr\nKe3BIH4LNM6enWjya/ENSIp1/0mGl6Ao/+gfeSUjfS3T2xf/ufRgCoNv6dGZ898f\nz0Tzl2MPvSyIb0AFny275plPL4YwxyHkkiRDjyp3negheNe2XDni5YIHrZendVVB\nU79C00sfiwKBgQDa7JtFyNXt5tf0/PvtNqZX/bNjgN3Zsdaq6jryDqg/1tgjx/Ob\nVq2CfGrBphvnkeMBfGS8v6fxi75Ex4ZlCtCw1Nx49WhQEBHugHrQRXSjg7wFukm/\nAMXWZtOHUPBvs+EusyvTNFbbFpzHA/1sVxVuxrIyo/F0XqzGZ1tZng3O4QKBgCKm\n4+9uZgB+9SSbUM3RSDivH2vgsTqXAEggAwYaoVsb7PI+tJUnJP2IWaXBVP8Ggjfj\nMwYIwfJk4m8wStjRKGc2BbIpkWpS1/fjj8RDPYSZecHXg1gzHSrbX4+u7MT3pPc2\ni51CLByV3wW0YwRooMUZVn4oHRthPXtVcyBnfKrnAoGBAMTwUweb3D9zbUUuP3ZQ\nJdVDHXWoxnTNlJTYx54i4Jr0VpJbLgbzyYYmSQ3dcGXSBj19ATHe4lCpCytfQNHV\ndDiTpMrxvPGhfrfyYeR0aDvLRQ2WBtyh8IOudLPUL+7QB/HqQt+tsP/iF817d31p\nvgCAwix0aS5pWX1951HuR6d9\n-----END PRIVATE KEY-----\n'
const REACT_APP_GOOGLE_SPREADSHEET_SCHEDULE_ACTIONS_LOG_CLIENT_EMAIL =
    'schedule-actions-log@schedule-actions-log.iam.gserviceaccount.com'
const REACT_APP_GOOGLE_SPREADSHEET_SCHEDULE_ACTIONS_LOG_SHEET_ID =
    '1-MBftqygEI20x12VuFDm_NGwsfPfDlzZHiAG3H_uKFA'

export {
    REACT_APP_AIDE_API_URL,
    REACT_APP_AIDE_API_KEY,
    REACT_APP_ADMIN_API_GLOVOAPP_URL,
    REACT_APP_CORS_ADMIN_API_GLOVOAPP_URL,
    REACT_APP_ONION_SLOTS_LINK,
    REACT_APP_FIREBASE_API_KEY,
    REACT_APP_FIREBASE_AUTH_DOMAIN,
    REACT_APP_FIREBASE_PROJECT_ID,
    REACT_APP_FIREBASE_STORAGE_BUCKET,
    REACT_APP_FIREBASE_SENDER_ID,
    REACT_APP_FIREBASE_APP_ID,
    REACT_APP_GOOGLE_SPREADSHEET_SCHEDULE_ACTIONS_LOG_PRIVATE_KEY,
    REACT_APP_GOOGLE_SPREADSHEET_SCHEDULE_ACTIONS_LOG_CLIENT_EMAIL,
    REACT_APP_GOOGLE_SPREADSHEET_SCHEDULE_ACTIONS_LOG_SHEET_ID,
}
